
if(QZONE.FP._t){QZONE.appPlatform=QZONE.FP._t.QZONE.appPlatform;}
QZONE.__DI__=QZONE.FP._t.QZONE.dataCenter.get('yellowDiamondInfo');QZONE.__V__=!!QZONE.FP.getVipStatus();QZONE.appVisibility={a203:QZONE.__V__,a305:QZONE.FP._t.QZONE.OFPConfig&&QZONE.FP._t.QZONE.OFPConfig.appVisibilityRule.a305,a4:QZONE.FP._t.QZONE.OFPConfig&&QZONE.FP._t.QZONE.OFPConfig.appVisibilityRule.a4};QZONE.AppMap={};var g_W_Domain=top.g_W_Domain||"https://qzonestyle.gtimg.cn/qzone/v5/app/js/w.qzone.qq.com",g_Base_Domain=top.g_Base_Domain||"https://qzonestyle.gtimg.cn/qzone/v5/app/js/base.qzone.qq.com",g_Main_Domain=top.g_Main_Domain||"https://qzonestyle.gtimg.cn/qzone/v5/app/js/users.qzone.qq.com",g_R_Domain=top.g_R_Domain||"https://qzonestyle.gtimg.cn/qzone/v5/app/js/r.qzone.qq.com",g_Apps_Domain="https://qzonestyle.gtimg.cn/qzone/v5/app/js/appsupport.qq.com";QZONE.AppMap.cgiMap={normal:{inviteURL:"http://"+g_Apps_Domain+"/cgi-bin/qzapps/appinvite_invite.cgi",inviteList:"http://"+g_Apps_Domain+"/cgi-bin/qzapps/appinvite_qqlist.cgi",userInfoURL:"http://"+g_Apps_Domain+"/cgi-bin/qzapps/appinvite_getuserinfo.cgi"},ranch:{inviteURL:"http://"+g_Main_Domain+"/cgi-bin/qzapp/ranchinvite_invite.cgi",inviteList:"http://"+g_Main_Domain+"/cgi-bin/qzapp/ranchinvite_qqlist.cgi",userInfoURL:"http://"+g_Main_Domain+"/cgi-bin/qzapp/ranchinvite_getuserinfo.cgi"}};QZONE.AppMap.appMap={ranch:{}}
var _Filter={guest:0xA0,owner:0x140,gf:0x20,gp:0x80,al:0x40,vs:0x04,del:0x02,beta:0x800};var nameFilter={al:{a305:"音乐"}};var connectAppList={a501d:{panelurl:"http://"+QZONE.FP._t.imgcacheDomain+"/qzone/beta/douban/bind.html"}};function refreshAppList(appId,isDeleted){if(typeof(QZONE.FP.refreshAppList)=="function"){QZONE.FP.refreshAppList();}}
function refreshNavBar(aid){var _w=QZONE.FP._t,_d=_w.QZONE.shop.customMenuData;if(!_d){return;}
var l=_d.items,res=[],_e=false;for(var i=0,len=l.length;i<len;++i){if(l[i].href==aid){_e=true;}else{res.push(l[i]);}}
if(!_e){return;}
_d.items=null;_d.items=_w.objectClone(res);_w.QZONE.shop.refreshMenu(_d);}
function descriptionFix(s){var fn,k;return s.replace(descriptionFix._RE,function(a,b){k=b.indexOf("|");fn=descriptionFix._fnMap[(k<0?b:b.substring(0,k))];if(typeof(fn)=="function"){return fn(b);}else{return a;}});}
descriptionFix._RE=/\{(.+?)\}/g;descriptionFix._fnMap={"vip":function(v){return'<a href="http://paycenter.qq.com/home/?aid=info.aprev" class="c_tx4" target="_blank" style="text-decoration:underline">加入黄钻贵族</a>';},"link":function(v){var l=v.split("|"),href,text;if(l&&l.length&&l.length>1){l.shift();href=l.shift();if(href.toLowerCase().indexOf("http://")!=0){href="http:///"+href;}
text=l.join("");if(!text){text=href};return'<a target="_blank" class="c_tx4 unline" href="'+href+'">'+text+'</a>';}else{return"";}}};function statistic(ref,p){QZONE.FP._t.pgvMainV5("https://qzonestyle.gtimg.cn/qzone/v5/app/js/app.qzone.qq.com",p);}/*  |xGv00|8300abe88bbaf1c9400031b53722839e */