(function(_wnd){_wnd.QZONE=_wnd.QZONE||{};_wnd.QZONE.preview=_wnd.QZONE.preview||{};_wnd.QZONE.preview.goPreview=function(evt,p,data,fm,opts){fm=fm||$("qz_v6_preview");data=data||{};opts=opts||{};var tmp,buff=[],_p=p,doc=_wnd.document,suf="",params={"user_platform":QZFL.userAgent.windows?QZFL.userAgent.windows<6?"os_winXp":"os_win7":"os_mac","loginuin":_p.g_iLoginUin,"imgcache_prefix":_p.g_SPrefix,"jsver":function(gv){var la=[];for(var k in gv)if(k.indexOf("_js")<0)la.push(k+":'"+gv[k]+"'");return la.length?
la.join():"t:''"}(_p.g_V),"province_code":1,"isp_code":1,"via_proxy":1,"clientip":"127.0.0.1","blog":"","photo":"","g5type":"M","uin":_p.g_iUin,"is_lite":0,"set_prefix":_p.g_Set,"proxy_prefix":_p.g_DPrefix,"dnsname":_p.g_dns_name,"isActivedIzoneV6":_p.g_IZone_Flag,"userbitmap":_p.g_UserBitmap,"loginbitmap":_p.g_LoginBitmap,"bstyle":_p.g_hasCustomStyle,"diytitle":QZFL.string.escString(typeof data.g_diyTitle!="undefined"?data.g_diyTitle:_p.g_diyTitle),"diyskin":QZFL.string.escString(typeof data.g_diySkin!=
"undefined"?data.g_diySkin:_p.g_diySkin),"sceneid":typeof data.g_SceneID!="undefined"?data.g_SceneID:_p.g_SceneID,"styleid":String(data.g_StyleID||_p.g_StyleID).replace("v6/",""),"fullMode":typeof data.g_fullMode!="undefined"?data.g_fullMode:_p.g_fullMode,"v6mode":typeof data.g_Mode!="undefined"?data.g_Mode:"gfp_fixed","frameStyle":typeof data.g_frameStyle=="undefined"?_p.g_frameStyle:data.g_frameStyle,"is_icstyle":typeof data.g_icLayout=="undefined"?_p.g_icLayout:data.g_icLayout,"xwmode":typeof data.g_xwMode==
"undefined"?_p.g_xwMode:data.g_xwMode,"isFriend":0,"Nowtime":_p.g_NowTime,"timestamp":_p.g_timestamp,"dressup":opts&&opts._7ddress?QZFL.lang.obj2str(data.g_Dressup?{items:data.g_Dressup.items,windows:data.g_Dressup.windows,diyitems:data.g_Dressup.diyitems}:{items:_p.g_Dressup.items,windows:_p.g_Dressup.windows,diyitems:_p.g_Dressup.diyitems}):QZFL.lang.obj2str(data.g_Dressup||_p.g_Dressup),"itemverinfo":"","flag":_p.g_StaticFlag,"transLevel":typeof data.g_TransparentLevel!="undefined"?data.g_TransparentLevel:
_p.g_TransparentLevel,"neatstyle":_p.g_neatstyle,"iweekday":typeof data.g_7DDressNo!="undefined"?data.g_7DDressNo:_p.g_7DDressNo,"isdirectapp":0,"bgscroll":typeof data.g_isBGScroll!="undefined"?data.g_isBGScroll:_p.g_isBGScroll,"opNickname":QZFL.string.escString(_p.ownerProfileSummary[0]),"opGender":QZFL.string.escString(_p.ownerProfileSummary[1]),"opAge":QZFL.string.escString(_p.ownerProfileSummary[2]),"opAddress":QZFL.string.escString(_p.ownerProfileSummary[3]),"opSpacename":QZFL.string.escString(_p.ownerProfileSummary[4]),
"opDescription":QZFL.string.escString(_p.ownerProfileSummary[5]),"opBirthday":QZFL.string.escString(_p.ownerProfileSummary[6]),"readonly":0,"errno":0,"enter_ic":0,"ic2alpha":true,"clientmode":"none","is_hidetitle":_p.g_isLite==1?1:0,"nick_name":_p.ownerProfileSummary[0],"space_name":_p.ownerProfileSummary[4],"space_desc":_p.ownerProfileSummary[5],"url_appname":"preview","qlogo_domain":'"'+(_p.qlogoDomain||"https://qzonestyle.gtimg.cn/qzone/v6/promotion/preview/store.qq.com")+'"',"space_url":_p.g_dns_name?"http://"+_p.g_dns_name+".qzone.qq.com/":"http://user.qzone.qq.com/"+
_p.g_iUin,"profile_avatar":window.g_userProfile?g_userProfile.avatar:"","profile_career":window.g_userProfile?g_userProfile.career:"","profile_company":window.g_userProfile?g_userProfile.company:"","profile_sex":window.g_userProfile?g_userProfile.sex:"","profile_sex_type":window.g_userProfile?g_userProfile.sex_type:"","profile_marriage":window.g_userProfile?g_userProfile.marriage:"","profile_constellation_type":window.g_userProfile?g_userProfile.constellation_type:"","profile_constellation":window.g_userProfile?
g_userProfile.constellation:"","profile_hco":window.g_userProfile?g_userProfile.hco:"","profile_hc":window.g_userProfile?g_userProfile.hc:"","profile_hp":window.g_userProfile?g_userProfile.hp:"","profile_province":window.g_userProfile?g_userProfile.province:"","profile_city":window.g_userProfile?g_userProfile.city:"","html_hotbar_res_ret":"0"};if((params.fullMode+"").indexOf("ofp")!=-1)params.fullMode=6;if(!fm){fm=doc.createElement("form");fm.id="qz_v6_preview";fm.method="post";doc.body.appendChild(fm)}else fm.innerHTML=
"";params.imgcache="https://qzonestyle.gtimg.cn/qzone/v6/promotion/preview/qzs.qq.com";params.qzonestyle="https://qzonestyle.gtimg.cn/qzone/v6/promotion/preview/qzonestyle.gtimg.cn";params.g_tk=QZFL&&QZFL.pluginsDefine&&QZFL.pluginsDefine.getACSRFToken?QZFL.pluginsDefine.getACSRFToken():"";for(var k in params){tmp=doc.createElement("input");tmp.type="hidden";tmp.name=k;tmp.value=params[k];fm.appendChild(tmp);buff.push(k)}var querystring=[];if(data.nobar)querystring.push("nobar=1");if(data.ot)querystring.push("ot=1");if(opts&&opts._7ddress)querystring.push("ddress=1");if(opts&&opts.from)querystring.push("from="+
opts.from);if(opts&&opts.hottag)querystring.push("hottag="+opts.hottag);if(opts&&opts.previewId)querystring.push("previewId="+opts.previewId);if(QZONE.dressDataCenter.getDressAid())querystring.push("aid="+QZONE.dressDataCenter.getDressAid());suf=querystring.join("&");fm.action="http://user.qzone.qq.com/"+_p.g_iUin+"/preview"+(suf&&"?"+suf);fm.target=data.nobar==1?opts.target||"_blank":"_top";suf=opts&&opts.hashStr?"#"+opts.hashStr:"";if(opts&&opts.hash)suf=suf?suf+"&"+opts.hash:"#"+opts.hash;if(QZFL.userAgent.webkit)suf=
suf?suf+"&"+(new Date).getTime():"#"+(new Date).getTime();suf&&(fm.action+=suf);tmp=doc.createElement("input");tmp.type="hidden";tmp.name="paramslist";tmp.value=buff.join();fm.appendChild(tmp);QZFL.cookie.set("fnc","preview","https://qzonestyle.gtimg.cn/qzone/v6/promotion/preview/qzone.qq.com",null,1/60);fm.submit()}})(window);
/*  |xGv00|87aa3dbe0f09d966319d1d614cbc1613 */