;(function(IPAY){var channels=["qdqb",'kj','bank','cft','cftCB'];if($.inArray(IPAY.current_channel,channels)>-1){$("#amount_input_field").after('<div id="lover_amount_field" class="control-group" style="display:none;"> <label class="control-label" data-type="amount_field_label">推荐购买：</label><div class="controls"><span class="title-primary"><a class="checkbox" id="lover_checkbox" href="javascript:void(0);"><i class="icon-checkbox"></i><span id="lover_title">情侣红钻</span></a></span>&nbsp;&nbsp;<input id="lover_amount_input" class="input-min" type="text" maxlength="3" data-value="其它" style="display:none;"/>&nbsp;&nbsp;<span id="lover_amount_unit" style="display:none">月&nbsp;&nbsp;</span><span class="help-inline">(5元/月)</span> <span id="lover_amount_helper" class="help-text"></span> <span id="lover_amount_warning" class="help-block"></span></div></div><div id="lover_uin_input_field" class="control-group" style="display:none;"><label id="lover_uin_field_label" class="control-label">选择情侣：</label><div class="controls"><span id="lover_uin_value" class="title-primary" style="display:none;"></span><div id="lover_uin_wrapper" class="input-append user-append open"><input id="lover_uin_input" class="input-user" type="text" maxlength="12" value="请输入您要绑定的情侣号码"><div class="dropdown"><div id="lover_list_outer" class="bind_friend"><div class="f_qqlist" id="lover_f_list" style="display: none;"></div><div class="f_qqlist" id="lover_f_search" style="display: none;"></div></div></div><span class="help-text"><a data-action="lover-show-friend-list" href="javascript:void(0);">好友列表</a></span></div><div id="lover_uin_tips" class="help-text">选择1位好友与您绑定情侣红钻，双方共享浪漫QQ图标、免费穿QQ秀等特权。</div><div id="lover_uin_warning" class="help-block"></div></div></div>');$("#lover_amount_field").show();}})(IPAY);var FRIEND_LIST_LOVER;(function(){var id=function(id){return document.getElementById(id);},htmlcode=function(str,isdecode){var ar=['&','&amp;','<','&lt;','>','&gt;',' ','&nbsp;','"','&quot;',"'",'&#39;','\\r','<br>','\\n','<br>'];if(isdecode)
ar.reverse();for(var i=0,r=str;i<ar.length;i+=2)
r=r.replace(new RegExp(ar[i],'g'),ar[1+i]);return r;},create=function(){var xhr;if(window.XMLHttpRequest){xhr=new XMLHttpRequest();}
else{try{xhr=new ActiveXObject("Msxml2.XMLHttp")}
catch(e){xhr=new ActiveXObject("Microsoft.XMLHttp")}}
return xhr;},hdl=function(result){var list=['<div class="f_list">'],content=result.split("&")[0].split("=")[1],div=document.createElement("div"),groups=content.split(",");FRIEND_LIST_LOVER.value=content;if(uin){var _myTitle='自己('+uin+')';list.push('<ul style="float: none;" id="l_group_self"><li qq="'+uin+'" name="自己" title="'+_myTitle+'"><a href="javascript:void(0);" onclick="FRIEND_LIST_LOVER.friend(this.parentNode);">'+_myTitle+'</a></li></ul>');}
for(var i=0;i<groups.length;i++){if(groups[i].length==0)
continue;var group_arr=groups[i].split("|"),groupName=htmlcode(decodeURIComponent(group_arr[0].replace(/\n|\r/g,'')))||"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";list.push("<div class='f_group_close' index='"+i+"'><a href='javascript:void(0);' onclick='FRIEND_LIST_LOVER.group(this.parentNode);'>"+groupName+"</a></div>");list.push("<ul style='display:none;float:none' id='l_group_"+i+"'>");try{var friendInGroup=group_arr[1].split("+");if(friendInGroup.length>1){for(var j=0;j<friendInGroup.length;j+=2){var friendName=htmlcode(decodeURIComponent(friendInGroup[j+1]).replace(/\n|\r/g,''))||"&nbsp;&nbsp;&nbsp;&nbsp;";var friendQQ=friendInGroup[j];list.push("<li qq='"+friendQQ+"' name='"+friendName+"' title='"+friendName+"("+friendQQ+")"+"'><a href='javascript:void(0);' onclick='FRIEND_LIST_LOVER.friend(this.parentNode);'>"+friendName+"("+friendQQ+")</a></li>");}}}
catch(e){}
list.push("</ul>");}
list.push("</div>");wrap.innerHTML=list.join("");addEvent(ipt,"keyup",FRIEND_LIST_LOVER.search);addEvent(ipt,"keydown",function(e){if(search.style.display!="none"&&e.keyCode==13){e.preventDefault&&e.preventDefault();e.returnValue=false;}});if(typeof FRIEND_LIST_LOVER.onLoaded==='function'){try{FRIEND_LIST_LOVER.onLoaded(content);}
catch(e){}}},ipt,wrap,search,uin;FRIEND_LIST_LOVER=function(_ipt,_wrap,_search,_uin){uin=_uin;ipt=id(_ipt);wrap=id(_wrap);search=id(_search);$.ajax({url:"/cgi-bin/personal/get_user_friends.cgi?sck="+hex_md5(LIB.cookie.get('skey')),type:'GET',async:true,cache:false,timeout:3000,success:function(res){hdl(res);}});};FRIEND_LIST_LOVER.onLoaded=function(){};FRIEND_LIST_LOVER.group=function(elem){var i=elem.getAttribute("index"),group=id("l_group_"+i),a=["f_group_close","f_group_open"],b=["none",""]
j=elem.className=="f_group_close"?1:0;elem.className=a[j];group.style.display=b[j];};FRIEND_LIST_LOVER.friend=function(elem){ipt.value=elem.getAttribute("qq");ipt.onchoose&&ipt.onchoose();wrap.style.display="none";search.style.display="none";};var index,count,setSearchIndex=function(ind){for(var i=0;i<count;i++){var elem=id("li_qq"+(i+1));if(elem&&i+1==ind){elem.className="f_search_cur_li"}
else{elem.className=""};}};FRIEND_LIST_LOVER.search=function(e){var e=e||window.event;switch(e.keyCode){case 38:index--;if(index<1){index+=count;}
setSearchIndex(index);e.preventDefault&&e.preventDefault();e.returnValue=false;return;case 40:index++;if(index>count){index-=count;}
setSearchIndex(index);e.preventDefault&&e.preventDefault();e.returnValue=false;return;case 13:if(search.style.display!="none"){var elem=id("li_qq"+index);FRIEND_LIST_LOVER.friend(elem);e.preventDefault&&e.preventDefault();e.returnValue=false;}
return;}
wrap.style.display="none";var val=ipt.value;if(val.length<1){wrap.style.display='';search.style.display='none';search.innerHTML="";return;}
var li=wrap.getElementsByTagName("li"),len=li.length,list=['<div class="f_list f_search"><ul style="float:none">'];count=0,index=1;var regQuote=function(str){return str.replace(/([\.\\\+\*\?\[\^\]\$\(\)\{\}\=\!\<\>\|\:\-])/g,"\\$1");}
for(var i=0;i<len;i++){var qq=li[i].getAttribute("qq"),regqq=new RegExp("^"+regQuote(val)+"\\d*"),name=li[i].getAttribute("name"),regname=new RegExp(regQuote(val));if((qq&&qq.match(regqq))||(name&&name.match(regname))){count++;list.push("<li qq='"+qq+"' id='li_qq"+(count)+"'>"+li[i].innerHTML+"</li>");}
if(count>4){break;}}
list.push("</ul></div>");search.innerHTML=list.join("");if(count>0){setSearchIndex(1);search.style.display="";}
else{search.style.display="none";}};var addEvent=function(elem,type,func){if(elem.addEventListener){elem.addEventListener(type,func,false);}
else{elem.attachEvent("on"+type,func);}};})();(function(ABTest,IPAY,LIB,FRIEND_LIST_LOVER){var _ipay=IPAY;var l={};l.cgi={discardUrl:"https://imgcache.qq.com/cgi-bin/account/get_qqshow_discountcard.cgi",loverUrl:"https://imgcache.qq.com/cgi-bin/account/get_open_service_list.cgi"};l.is_renewer=false;l.is_select_lover=false;l.is_select_card=false;l.months=0;l.lover_num=null;l.card_info={cardID:"",minMonth:"",dis:""};l.channels=["qdqb",'kj','bank','cft','cftCB'];l.memory={before:new Function()};l.init=function(){l.event();$.ajax({url:l.cgi.loverUrl,type:'GET',dataType:'json',cache:false,timeout:3000,success:function(res){if(res.resultcode==0){var list=res.resultinfo.list,c={};for(var i=0,j=list.length;i<j;i++){if(list[i].servicecode=="QLHZ"){l.is_renewer=true;$("#lover_uin_input_field").hide();$("#lover_title").html("续费情侣红钻");break;}}}}});FRIEND_LIST_LOVER.friend=function(node){if(node){var _uin=node.getAttribute('qq');$('#lover_f_search').hide();l._friendListToggle(false);$('#lover_uin_input').val(_uin);if(_uin==_ipay.target_uin){l._setLvQqWarning("<i class='icon-help'></i>不能选择自己作为绑定对象");}
else{l.lover_num=_uin;}}};FRIEND_LIST_LOVER('lover_uin_input','lover_f_list','lover_f_search',_ipay.target_uin);};l._friendListToggle=function(show){var $fList=$('#lover_f_list'),state=$fList.data('state'),_hide=function(){$fList.data('state','hide').hide();},_show=function(){$fList.data('state','show').show();};if(typeof show==='undefined'){!state||state==='hide'?_show():_hide();}
else{show?_show():_hide();}};l.event=function(){$("#lover_checkbox").bind('click',function(e){_ipay._clearAmountWarning();var _node=$(this).parents("span");var flag=_node.hasClass('selected')?false:true;l.selectLover(flag);l.updatePrice();});$(document).bind('click',function(){$('#lover_f_search').hide();l._friendListToggle(false);});$('a[data-action="lover-show-friend-list"]').on('click',function(e){if(!_ipay._formLocked){l._friendListToggle(true);$('#lover_uin_input').val("请输入您要绑定的qq号码").focus().select();$("#balance_tips").hide();}
e.stopPropagation();});$('#lover_uin_input').focus(function(e){l._clearLvQqWarning();if(!this.value){$('#l_f_search').empty();l._friendListToggle(true);}
$(this).one('mouseup',function(e){e.preventDefault();}).select();});$('#lover_uin_input').keyup(function(e){var m=$("#lover_uin_input").val()?$("#lover_uin_input").val().replace(/[^\d]/g,''):"";$("#lover_uin_input").val(m);l.lover_num=m;});$('#lover_uin_wrapper').find('div.dropdown,input').click(function(e){e.stopPropagation();});$("#amount_input").bind("keyup",function(e){_ipay._clearAmountWarning();var amount_val=$('#amount_input').val();var amount=_ipay.pay_mode=="year"?12*amount_val:amount_val;if(l.is_select_lover){if(amount<l.months){l._setLvMonthWarning();}
else{l._clearLvMonthWarning();}
l.updatePrice();}
if(l.is_select_card){_ipay._amountValidate();}});$("#lover_amount_input").bind('keyup',function(e){$("#balance_tips").hide();var m=$("#lover_amount_input").val()?$("#lover_amount_input").val().replace(/[^\d]/g,''):"";$("#lover_amount_input").val(m);if(m>_ipay.amount){l._setLvMonthWarning();}
else{l._clearLvMonthWarning();}
l.months=m;$("#lover_month").val(m);l.updatePrice();});};l.selectLover=function(flag){_ipay._clearAmountWarning();var _node=$("#lover_checkbox").parents("span");if(!flag){l.is_select_lover=false;_ipay.scene=="minipay"?"":_ipay.enableSend(true);_node.removeClass('selected');$("#lover_amount_input,#lover_amount_unit,#lover_uin_input_field").hide();l._clearLvMonthWarning();_ipay.data.price=_ipay.data.orgPrice;}
else{l.is_select_lover=true;l.is_select_card=false;_ipay.enableSend(false);_node.addClass('selected');$("#lover_amount_input,#lover_amount_unit").show();l.is_renewer?$("#lover_uin_input_field").hide():$("#lover_uin_input_field").show();$("#xxqqf_discard_field").find('label[data-action="l_show_list"]').html("请选择折扣卡");$('div[data-type="discard_list_wrapper"]').removeClass('open');$("#lover_amount_input").val(_ipay.amount).focus();l.months=_ipay.amount;_ipay.data.minAmount=1;}};l.selectCard=function(name,value){$("#xxqqf_discard_field").find('label[data-action="l_show_list"]').html(name);$('div[data-type="discard_list_wrapper"]').removeClass('open');if(value=="0"){l.is_select_card=false;_ipay.data.price=_ipay.data.orgPrice;l.updatePrice();return;}
var s=value.split("$");l.card_info.cardId=s[0];l.card_info.minMonth=s[1];l.card_info.dis=s[2];_ipay.enableSend(false);_ipay.data.minAmount=l.card_info.minMonth;_ipay._amountValidate();l.updatePrice();};l.updatePrice=function(){var price,amount_val=$('#amount_input').val();var amount=_ipay.pay_mode=="year"?12*amount_val:amount_val;if(l.is_select_lover&&amount>0){price=(amount*_ipay.data.orgPrice+l.months*5)/amount;}
if(l.is_select_card&&amount>0){price=_ipay.data.orgPrice*l.card_info.dis;}
_ipay.data.price=price?price:_ipay.data.price;_ipay.onAmountChange(amount);};l.verify=function(){if(l.is_select_lover){if(_ipay.amount<l.months)
return false;if(!l.is_renewer&&!l.lover_num&&l.lover_num!="请输入您要绑定的qq号码"){this._setLvQqWarning();return false;};}
return true;};l._setLvQqWarning=function(warning){$("#lover_uin_input_field").addClass("warning");$("#lover_uin_warning").html(warning?warning:"<i class='icon-help'></i>请输入您需要绑定的情侣号码");};l._clearLvQqWarning=function(){$("#lover_uin_input_field").removeClass("warning");$("#lover_uin_warning").html("");};l._setLvMonthWarning=function(){$("#lover_amount_field").addClass("warning");$("#lover_amount_warning").html("<i class='icon-help'></i>输入不能大于红钻开通月数");};l._clearLvMonthWarning=function(){$("#lover_amount_field").removeClass("warning");$("#lover_amount_warning").html("");};l._setLvCardTips=function(){$("#discard_selector_warning").html("注：开情侣红钻不能使用折扣卡");};l._clearLvCardTips=function(){$("#discard_selector_warning").html("");};if(_ipay.scene==='pay'||_ipay.scene==='minipay'){l.init();}
ABTest.after(IPAY,'selectPayMode',function(){var _ipay=IPAY;var _channel=_channel?_channel:IPAY.current_channel;if($.inArray(_channel,l.channels)>-1){if(l.is_select_lover){var m=$("#lover_amount_input").val()?$("#lover_amount_input").val().replace(/[^\d]/g,''):"";$("#lover_amount_input").val(m);if(m>_ipay.amount){l._setLvMonthWarning();}
else{l._clearLvMonthWarning();}
l.updatePrice();}
if(l.is_select_card){_ipay._amountValidate();l.updatePrice();}}});ABTest.before(IPAY,'selectChannel',function(_channel,_callback){var _ipay=IPAY;_channel=_channel?_channel:IPAY.current_channel;if($.inArray(_channel,l.channels)==-1){$("#lover_amount_field,#lover_uin_input_field").hide();_ipay.data.code="xxqqf";_ipay.data.price=_ipay.data.orgPrice;_ipay.onAmountChange(_ipay.amount);_ipay.scene=="minipay"?"":_ipay.enableSend(true);}
else{if(_ipay.target_uin==_ipay.uin){if(l.is_select_lover){_ipay.enableSend(false);}
if(l.is_select_card){l.is_select_card=false;_ipay.data.price=_ipay.data.orgPrice;}
$("#lover_amount_field").show();l.updatePrice();}else{$("#lover_amount_field,#lover_uin_input_field").hide();_ipay.data.code="xxqqf";_ipay.data.price=_ipay.data.orgPrice;_ipay.onAmountChange(_ipay.amount);}};var newCallback=function(){typeof _callback==='function'&&_callback();_ipay.current_channel=="qdqb"&&$.ajax({url:l.cgi.discardUrl,type:'GET',dataType:'json',cache:false,timeout:5000,success:function(res){if(res.resultcode==0){var list=res.resultinfo.list,_v="";for(var i=0,j=list.length;i<j;i++){_v+='<li><a title="'+list[i].cardname+'" data-action="select_item" value="'+list[i].cardid+"$"+list[i].minmonth+"$"+list[i].discount/100+'" href="javascript:void(0);">'+list[i].cardname+'</a></li>';};if(list.length>0){$("#xxqqf_discard_field").delegate('[data-action="l_show_list"]','click',function(e){if(_ipay._formLocked)
return;if(l.is_select_lover){$("#discard_selector_warning").html("注：开情侣红钻不能使用折扣卡");return;}
else{$("#discard_selector_warning").html("");}
var $wrapper=$(this).parent().toggleClass('open');$('div[data-type="discard_list_wrapper"]').not($wrapper).removeClass('open');e.stopPropagation();}).delegate('[data-action="select_item"]','click',function(){var v=$(this).attr("value"),n=$(this).attr("title");l.is_select_card=true;l.selectCard(n,v);});_v+='<li><a title="请选择折扣卡" data-action="select_item" value="0" href="javascript:void(0);">不使用折扣卡</a></li>';$("#discard_selector").find('ul[class="list-menu"]').html(_v);$("#xxqqf_discard_field").show();}}}});};return[_channel,newCallback];});ABTest.before(IPAY,"submit",function(_opts){if($.inArray(IPAY.current_channel,l.channels)>-1){if(!l.verify()){_opts.before=function(){return false;};return false;}
if(l.is_select_lover){_ipay.data.code="qlhzhh";_opts.data["open_detail"]='XXQQF_'+31*_ipay.amount+",QLHZ_"+31*l.months;l.is_renewer?"":_opts.data['lover_num']=l.lover_num;}
else{_ipay.data.code="xxqqf";}
if(l.is_select_card&&IPAY.current_channel=="qdqb"){_opts.data["qqshow_discountcard_id"]=l.card_info.cardId;}}
else{_ipay.data.code="xxqqf";}
return _opts;});ABTest.before(IPAY,"_doChannelCallback",function(res){if(res.open_detail&&IPAY.data.code=="qlhzhh"){var _d=res.open_detail.split(";");var _dql=_d[0].split(",");IPAY.langs.success_for_self+=parseInt(_dql[1]/31,10)>0?("，"+parseInt(_dql[1]/31,10)+"个月情侣红钻"):"";}});})(ABTest,IPAY,LIB,FRIEND_LIST_LOVER);/*  |xGv00|b4e7eb957f6542988056e3e264e79a68 */