var auth_code={
    'LTMCLUB' :1,
    'XXQQF'   :2,
    'XXQGAME' :3,
    'XXJZGW'  :4,
    'LTQQX'   :5,
    'XXYYSJ'  :6,
    'SHSQ'    :7,
    'WEYY'    :8,
    'XWTT'    :9,
    'QWYYHY'  :10,
    'QWYXYYRL':11,
    'YXYYRL'  :12,
    'OTALTQE' :13,
    'STKLTQE' :14,
    'LTQE'    :15,
    'QWLTQE'  :16,
    'QWXWYLYJ':17,
    'LTWXCLUB':18,
    'XWYLYJ'  :19,
    'LTQEZX'  :20,
    'XWTYKX'  :22,
    'QWXWTYKX':23,
    'YYHY'    :24,
    'QWXWTT'  :25,
    'QWSHSQ'  :26,
    'QWWEYY'  :27,
    'WDYYHY'  :28,
    'YKQZONE' :29,
    'QZYXC'   :30,
    'QQLOVE'  :31,
    'XXLOVE'  :32,
    'XXQQPAY' :33,
    'WDYLC'   :34,
    'QWXXQQF' :35,
    'QWXXJZGW':36,
    'PETSJ'   :37,
    'PETVIP'  :38,
    'YXXYQH'  :39,
    'WDSSX'   :40,
    'XXSQQ'   :41,
    'QWXXSQQ' :42,
    'YKSJJLB' :43,
    'LTSXDX'  :44,
    'XXJD'    :45,
    'QQPETWX' :46,
    'WDYXMS'  :47,
    'SJCLUB'  :48,
    'DDCLUB'  :49,
    'WDYLWX'  :50,
    'ZZXYYDD' :51,
    'ZZXSJKJ' :52,
    'YKPET'   :53,
    'YKSJYY'  :54,
    'QQCSDR'  :55,
    'YKKLCY'  :56,
    'YXQQC'   :57,
    'EMKJRTT' :58,
    'WDSJQX'  :59,
    'YKMZ'    :60,
    'SHQX'    :61,
    'YKXSQQ'  :62,
    'WDJYDD'  :63,
    'CJHYMDO' :64
};